course/urls.py
from unicodedata import name
from django.urls import path
from course.views import CategoryView, CategoryCourses, NewCourse, Enroll, DeleteCourse, EditCourse, MyCourses, CourseDetail, Submissions, StudentSubmissions, GradeSubmission

from module.views import NewModule, CourseModules
from page.views import NewPageModules, PageDetail
from exam.views import NewExam, NewQuestion, ExamDetail, TakeExam, SubmitAttempt, Result
from assignment.views import NewAssignment, AssignmentDetail, NewSubmission
urlpatterns = [
    # Course - Views
    path('newcourse/', NewCourse, name="newcourse"),
    path('mycourses/', MyCourses, name='my-courses'),
    path('category/', CategoryView , name='category'),
    path('category/<category_slug>', CategoryCourses, name='category-courses'),
    path('<course_id>', CourseDetail, name='course'),
    path('<course_id>/enroll', Enroll, name='enroll'),
    path('<course_id>/edit', EditCourse, name='edit-course'),
    path('<course_id>/delete', DeleteCourse, name='delete-course'),

    # Modules - Views
    path('<course_id>/modules', CourseModules, name='modules'),
    path('<course_id>/modules/newmodule', NewModule, name='new-module'),

    # Page - Views (since it's connected to exam view it need /pages/)
    path('<course_id>/module/<module_id>/pages/newpage', NewPageModules, name='new-page'),
    path('<course_id>/module/<module_id>/pages/<page_id>', PageDetail, name='page-detail'),

    # Exam - Views
    path('<course_id>/module/<module_id>/exam/newexam', NewExam, name='new-exam'),
    path('<course_id>/module/<module_id>/exam/<exam_id>/newquestion', NewQuestion, name='new-question'),
    path('<course_id>/module/<module_id>/exam/<exam_id>/', ExamDetail, name='exam-detail'),
    path('<course_id>/module/<module_id>/exam/<exam_id>/take', TakeExam, name='take-exam'),
    path('<course_id>/module/<module_id>/exam/<exam_id>/take/submit', SubmitAttempt, name='submit-exam'),
    path('<course_id>/module/<module_id>/exam/<exam_id>/<attempt_id>/results', Result, name='result'),

    # Assignment - Views
    path('<course_id>/module/<module_id>/assignment/newassignment', NewAssignment, name='new-assignment'),
    path('<course_id>/module/<module_id>/assignment/<assignment_id>', AssignmentDetail, name='assignment-detail'),
    path('<course_id>/modules/<module_id>/assignment/<assignment_id>/start', NewSubmission, name='start-assignment'),

    # Submission - Views
    path('<course_id>/submissions', Submissions, name='submissions'),
    path('<course_id>/studentsubmissions', StudentSubmissions, name='student-submissions'),
    path('<course_id>/submissions/<grade_id>/grade', GradeSubmission, name='grade-submission'),
]

student_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from onlinecourse.views import UserProfile
from course.views import index, listing

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('onlinecourse.urls')),
    path('course/', include('course.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('<username>', UserProfile, name='profile'),
    path('home/', listing, name='home'),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/models.py
from email.policy import default
from enum import auto
from multiprocessing.connection import answer_challenge
from tracemalloc import get_object_traceback
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
# Answer model
class Answer(models.Model):
    answer_text = models.CharField(max_length=900)
    is_correct = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer_text

# Question model
class Question(models.Model):
    question_text = models.CharField(max_length=900)
    answers = models.ManyToManyField(Answer)
    points = models.PositiveIntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text
# Exam model
class Exams(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = RichTextField()
    date = models.DateTimeField(auto_now_add=True)
    due = models.DateField()
    allowed_attempts = models.PositiveIntegerField()
    time_limit_mins = models.PositiveIntegerField()
    questions = models.ManyToManyField(Question)

    def __str__(self):
        return self.title

# Learner model
class Learner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exams, on_delete=models.CASCADE)
    score = models.PositiveIntegerField()
    completed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

# Get number of attempt objects
class Attempt(models.Model):
    exam = models.ForeignKey(Exams, on_delete=models.CASCADE)
    # One Learner has many attempt
    learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete= models.CASCADE)

    # Save the attempt results to get score and show on result page
    def __str__(self):
        return self.learner.user.username + ' - ' + self.answer.answer_text

exam/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from exam.models import Answer, Exams, Question, Answer

# Page Form
class NewExamForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate'}), required=True)
    description = forms.CharField(widget=CKEditorWidget())
    # Allow form to pick and validate the date
    due= forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}), required=True)
    allowed_attempts = forms.IntegerField(max_value=100, min_value=1)
    time_limit_mins = forms.IntegerField(max_value=360, min_value=10)

    class Meta:
        model = Exams
        fields = ('title', 'description', 'due', 'allowed_attempts', 'time_limit_mins')

class NewQuestionForm(forms.ModelForm):
    question_text = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate'}), required=True)
    points = forms.IntegerField(max_value=10, min_value=1)

    class Meta:
        model = Question
        fields = ('question_text', 'points')

class NewAnswerForm(forms.ModelForm):
    answer_text = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate'}), required=True)
    is_correct = forms.BooleanField(required=True)

    class Meta:
        model = Answer
        fields = ('answer_text', 'is_correct')

exam/views.py
from audioop import add
from multiprocessing import context
from pyexpat import model
from turtle import title
from venv import create
from django.shortcuts import render, redirect, get_object_or_404
from urllib import request
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.contrib.auth.models import User

from exam.forms import NewExamForm, NewQuestionForm
from exam.models import Answer, Question, Exams, Learner, Attempt
from module.models import Module

# Create your views here.
# Create new exam view
# Rememeber to add id to match url path
def NewExam(request, course_id, module_id):
    user = request.user
    module = get_object_or_404(Module, id=module_id )

    if request.method == 'POST':
        form = NewExamForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')
            due = form.cleaned_data.get('due')
            allowed_attempts = form.cleaned_data.get('allowed_attempts')
            time_limit_mins = form.cleaned_data.get('time_limit_mins')
            exam = Exams.objects.create(user=user, title=title, description=description, due=due, allowed_attempts=allowed_attempts, time_limit_mins=time_limit_mins)
            module.exams.add(exam)
            module.save()
            return redirect('new-question', course_id=course_id, module_id=module_id, exam_id=exam.id)

    else:
        form = NewExamForm()

    context = {
        'form': form,
    }
    return render(request, 'exam/newexam.html', context)

# Create new question view
def NewQuestion(request, course_id, module_id, exam_id):
    user = request.user
    exam = get_object_or_404(Exams, id=exam_id)

    if request.method == 'POST':
        form = NewQuestionForm(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data.get('question_text')
            points = form.cleaned_data.get('points')
            # Get answer key and objects key into the question form 
            # QueryDict.getlist(key, default=None) Returns a list of the data with the requested key. Returns an empty list if the key doesn’t exist and default is None.
            #It’s guaranteed to return a list unless the default value provided isn’t a list.
            answer_text = request.POST.getlist('answer_text')
            is_correct = request.POST.getlist('is_correct')
            question = Question.objects.create(question_text=question_text, user=user, points=points)

            # Since answer is many to many fields, need to call zip() function to create tuples of each list based on the no.index (answer , is_correct)
            for a, c in zip(answer_text, is_correct):
                answer = Answer.objects.create(answer_text=a, is_correct=c, user=user)
                question.answers.add(answer)
                question.save()
                exam.questions.add(question)
                exam.save()
            return redirect('new-question', course_id=course_id, module_id=module_id, exam_id=exam.id)
    else:
        form = NewQuestionForm()

    context = {
        'form': form,
    }
    return render(request, 'exam/newquestion.html', context)

# Show exam detail view
def ExamDetail(request, course_id, module_id, exam_id):
    user = request.user
    exam = get_object_or_404(Exams, id=exam_id)
    my_attempts = Learner.objects.filter(exam=exam, user=user)

    context = {
        'exam': exam,
        'my_attempts': my_attempts,
        'course_id': course_id,
        'module_id': module_id,
    }
    return render(request, 'exam/examdetail.html', context)

# Exam views for learner
def TakeExam(request, course_id, module_id, exam_id):
    exam = get_object_or_404(Exams, id=exam_id)
    context = {
        'exam': exam,
        'course_id': course_id,
        'module_id': module_id,
    }
    return render(request, 'exam/takeexam.html', context)

# Get exam submission view
def SubmitAttempt(request, course_id, module_id, exam_id):
    user= request.user
    exam = get_object_or_404(Exams, id=exam_id)
    earned_points = 0
    if request.method == 'POST':
        questions = request.POST.getlist('question')
        answers = request.POST.getlist('answer')
        learner = Learner.objects.create(user=user, exam=exam, score=0)

        # Add question's and submitted answer's id to a tubple with zip function
        for q, a in zip(questions, answers):
            question = Question.objects.get(id=q)
            answer = Answer.objects.get(id=a)
            Attempt.objects.create(exam=exam, learner=learner, question=question, answer=answer)
            
            # Get score
            if answer.is_correct == True:
                earned_points += question.points
                learner.score += earned_points
                learner.save()
        return redirect('index')

# Show result view
def Result(request, course_id, module_id, exam_id, attempt_id):
    user = request.user
    exam = get_object_or_404(Exams, id=exam_id)
    attempts = Attempt.objects.filter(exam=exam, learner__user=user)

    context = {
        'exam': exam,
        'attempts': attempts,
        'course_id': course_id,
        'module_id': module_id,
    }
    return render(request, 'exam/result.html', context)

student_portal/templates/exam/examdetail.html
{% extends 'base.html' %}
{% load static %}

<!-- Page Detail-->
{% block content %}
<div class="section">
    <h2><b>{{ exam.title }}</b></h2>
    <div class="divider">

    </div>
</div>

<div class="row">
    <div class="col s4">
        <h5>Due:</h5>
        <p>{{ exam.due }}</p>
    </div>

    <div class="col s4">
        <h5>Allowed Attempt: </h5>
        <p>{{ exam.allowed_attempts }}</p>
    </div>

    <div class="col s4">
        <h5>Time limit:</h5>
        <p>{{ exam.time_limit_mins }} minutes</p>
    </div>

    <div class="col s12">
        {{ exam.description | safe }}
    </div>
</div>
    <!-- Show user attempt-->
    <div class="col s12">
        <ul class="collection with-header">
            <li class="collection-header"><h4>My attempts</h4></li>
            {% for attempt in my_attempts %}
            <li class="collection-item"><a href="{% url 'result' course_id module_id exam.id attempt.id %}"><h5>Scores: {{ attempt.score }}</h5></a></li>
            {% endfor %}
          </ul>    
    </div>
    <div class="field center-align">
        <a class="btn  waves-effect waves-light" href="{% url 'take-exam' course_id module_id exam.id %}">Take Exam</a>
      </div>
</div>

{% endblock %}

student_portal/templates/exam/newexam.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row center-align">
    <div class="col s12">

        <form method="post" enctype="multipart/form-data" action="" role="form">
            {% csrf_token %}
            <h3 class="title is-3">Create a New Exam</h3>

            <div class="input-field">
                {{ form.title }}
                <label for="title">Title</label>
            </div>
            <div class="divider"></div>

            <div class="input-field col s12">
                {{ form.description }}
                <label for="description">Description</label>
            </div>

            <div class="input-field col s12">
                {{ form.due }}
                <label for="due">Due</label>
            </div>

            <div class="input-field col s12">
                {{ form.allowed_attempts }}
                <label for="allowed_attempts">Allowed Attempts</label>
            </div>

            <div class="input-field col s12">
                {{ form.time_limit_mins }}
                <label for="time_limit_mins">Time Limit</label>
            </div>

            <div class="row">
                <div class="col s12">
                    <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
                </div>
            </div>

            <div class="field">
                <button class="btn waves-effect waves-light" type="submit" name="action">Create Exam
                    <i class="material-icons right">class</i>
                </button>
            </div>

        </form>
    </div>
</div>

{% endblock %}

student_portal/templates/exam/newquestion.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row center-align">
  <div class="col s12">
<!--update idea: Add a container show created questions for the exam-->
    <form method="post" enctype="multipart/form-data" action="" role="form">
      {% csrf_token %}
      <h3 class="title is-3">Create a New Question</h3>

      <div class="input-field">
        {{ form.question_text }}
        <label for="question_text">Question</label>
      </div>
      <div class="divider"></div>

      <div class="input-field col s12">
        {{ form.points }}
        <label for="points">Point(s)</label>
      </div>

      <!--Answer List-->
      <div class="input-field col s9">
        <input type="text" name="answer_text" id="id_answer_text" class="validate">
        <label for="answer_text">Answer 1</label>
      </div>
      <div class="input-field col s3">
        <select id="id_is_correct" name="is_correct">
          <option value="" disabled selected>Choose yes or no</option>
          <option value="True">Yes</option>
          <option value="False">No</option>
        </select>
        <label>Is this answer correct?</label>
      </div>

      <div class="input-field col s9">
        <input type="text" name="answer_text" id="id_answer_text" class="validate">
        <label for="answer_text">Answer 2</label>
      </div>
      <div class="input-field col s3">
        <select id="id_is_correct" name="is_correct">
          <option value="" disabled selected>Choose yes or no</option>
          <option value="True">Yes</option>
          <option value="False">No</option>
        </select>
        <label>Is this answer correct?</label>
      </div>

      <div class="input-field col s9">
        <input type="text" name="answer_text" id="id_answer_text" class="validate">
        <label for="answer_text">Answer 3</label>
      </div>
      <div class="input-field col s3">
        <select id="id_is_correct" name="is_correct">
          <option value="" disabled selected>Choose yes or no</option>
          <option value="True">Yes</option>
          <option value="False">No</option>
        </select>
        <label>Is this answer correct?</label>
      </div>

      <div class="input-field col s9">
        <input type="text" name="answer_text" id="id_answer_text" class="validate">
        <label for="answer_text">Answer 4</label>
      </div>
      <div class="input-field col s3">
        <select id="id_is_correct" name="is_correct">
          <option value="" disabled selected>Choose yes or no</option>
          <option value="True">Yes</option>
          <option value="False">No</option>
        </select>
        <label>Is this answer correct?</label>
      </div>

      <div class="row">
        <div class="col s12">
          <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
        </div>
      </div>
      <div class="col s12">
        <p class="controll">
          <button class="btn waves-effect waves-light" type="submit" value="login">Create Question
            <i class="material-icons right">class</i>
          </button>
        </p>
      </div>
      <div class="col s12">
        <button href="{% url 'my-courses' %}" class="btn waves-effect waves-light">Finish
          <i class="material-icons right">send</i>
        </button>
      </div>

    </form>
  </div>
</div>

{% endblock %}

student_portal/templates/exam/result.html
{% extends 'base.html' %}
{% load static %}

<!-- Page Detail-->
{% block content %}
<div class="section">
    <h2><b>{{ exam.title }}</b></h2>
    <div class="divider">

    </div>
</div>

<div class="row">
    <div class="col s4">
        <h5>Due:</h5>
        <p>{{ exam.due }}</p>
    </div>

    <div class="col s4">
        <h5>Time limit:</h5>
        <p>{{ exam.time_limit_mins }} minutes</p>
    </div>

    <div class="col s12">
        {{ exam.description | safe }}
    </div>
</div>
    <!-- Show user attempt-->
    <div class="col s12">
        <form method="post" action="{% url 'submit-exam' course_id module_id exam.id %}" role="form" class="col s12">
            {% csrf_token %}
            {% for question in exam.questions.all %}
            <div class="col s12">
                <br>
                <p>{{ question.question_text }}</p>
                <!-- To get question.id, set the input & value here-->
                <input type="hidden" name="question" value="{{ question.id }}">
            </div>
            <!--Load answer and add name tag to the input and check the correct answer-->
            {% for answer in question.answers.all %}
            <div class="input col s12">
                <label>
                    <input name="answer" type="checkbox" disabled="disabled" value="{{ answer.id }}" {% if answer.is_correct == True %}checked="checked" {% endif %}/>
                    <span>{{ answer.answer_text }}</span>
                </label>
            </div>
            {% endfor %}
            {% endfor %}
        </form> 
    </div>
    <!--Show the learner's selected answers-->
    <div class="section">
        <h5>Your answer</h5>
        <div class="divider"></div>
            {% for attempt in attempts %}
            <h6 class="{% if attempt.answer.is_correct == True %}green{% else %}red{% endif %}-text text-darken-2"><b>{{ attempt.answer.answer_text }}</b></h6>
            {% endfor %}

    </div>
</div>

{% endblock %}

student_portal/templates/exam/takeexam.html
{% extends 'base.html' %}
{% load static %}

<!-- Page Detail-->
{% block content %}
<div class="section">
    <h2><b>{{ exam.title }}</b></h2>
    <div class="divider"></div>
</div>

<div class="row">
    <div class="col s4">
        <h5>Due:</h5>
        <p>{{ exam.due }}</p>
    </div>

    <div class="col s4">
        <h5>Time limit:</h5>
        <p>{{ exam.time_limit_mins }} minutes</p>
    </div>

</div>
<!-- Show user attempt-->
<div class="col s12">
    <form method="post" action="{% url 'submit-exam' course_id module_id exam.id %}" role="form" class="col s12">
        {% csrf_token %}
        {% for question in exam.questions.all %}
        <div class="col s12">
            <br>
            <p>{{ question.question_text }}</p>
            <!-- To get question.id, set the input & value here-->
            <input type="hidden" name="question" value="{{ question.id }}">
        </div>
        <!--Load answer and add name tag to the input-->
        {% for answer in question.answers.all %}
        <div class="input col s12">
            <label>
                <input name="answer" type="checkbox" value="{{ answer.id }}">
                <span>{{ answer.answer_text }}</span>
            </label>
        </div>
        {% endfor %}
        {% endfor %}

        <div class="field">
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </div>
    </form>
</div>

{% endblock %}